development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE_NAME"] %>_development
  pool: 5
  username: <%= ENV["DATABASE_NAME"] %>
  password: <%= ENV["DATABASE_PASS"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE_NAME"] %>_test
  pool: 5
  username: <%= ENV["DATABASE_NAME"] %>
  password: <%= ENV["DATABASE_PASS"] %>
